name: Main Pipeline

on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: "18"

  docker:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: "day-48-node-app"
      tag: ${{github.sha}}
    secrets:
      docker_username: ${{secrets.docker_username}}
      docker_token: ${{secrets.docker_token}}


  security-scan:
    needs: docker
    runs-on: ubuntu-latest
    env:
        IMAGE: ${{ secrets.docker_username }}/day-48-node-app:${{ github.sha }}
    steps:

      - name: Debug Image
        run: echo "$IMAGE"

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{env.IMAGE}}
          format: table
          exit-code: 1
          severity: CRITICAL

  deploy:
    needs: [security-scan]
    runs-on: ubuntu-latest
    environment: production
    env:
       IMAGE: " ${{secrets.docker_username}}/day-48-node-app:${{github.sha}}"

    steps:
      - name: Deploy
        run: 'echo "Deploying $IMAGE to production"'