name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: "18"

  docker:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: "day-48-node-app"
      tag: latest

    secrets:
      docker_username: ${{ secrets.docker_username }}
      docker_token: ${{ secrets.docker_token }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Deploying ${{ needs.docker.outputs.image_url }} to production"