name: Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
    outputs:
      # LAYER 3: The "Caller" sees this. It MUST point to the job output.
      image_url:
        description: "The full image name and tag"
        value: ${{ jobs.build.outputs.final_image_string }}

jobs:
  build:
    runs-on: ubuntu-latest
    # LAYER 2: The Job level. It MUST point to the step output.
    outputs:
      final_image_string: ${{ steps.meta.outputs.step_output_var }} 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login Docker
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Set image metadata
        id: meta
        shell: bash
        run: |
          # LAYER 1: The Step level.
          # Create the string and push it to $GITHUB_OUTPUT
          IMAGE_PATH="${{ secrets.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}"
          
          echo "step_output_var=$IMAGE_PATH" >> $GITHUB_OUTPUT
          
          # CRITICAL DEBUG: Check your GitHub logs for this line!
          # If this prints "/day-48-node-app:latest", your secret is empty.
          echo "DEBUG: The value being sent to output is: $IMAGE_PATH"

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.step_output_var }}